<?xml version="1.0" encoding="utf-8"?><Database Name="restaurantdb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=restaurantdb;Integrated Security=True" SettingsObjectName="Dranken2.Properties.Settings" SettingsPropertyName="restaurantdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dranken" Member="Drankens">
    <Type Name="Dranken">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soort" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prijs" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>